spring:
  application:
    name: FOODFRENZY-API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://FOODFRENZY-AUTH-SERVICE
          predicates:
            - Path=/api/auth/**